### ISSUE TITLE
Made a neat audio station script!

### ISSUE THREAD

**Issue by SuperSonicHub1** [schollz/streamyouraudio#2]
Made a neat little script with [yt-dlp](https://github.com/yt-dlp/yt-dlp) in order to stream the entirety of what the program considers a "playlist" (YouTube playlist, Bandcamp album, [etc.](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md))

```bash
#!/bin/bash

yt-dlp-to-ffconcat() {
	local url=$1
	yt-dlp --format bestaudio --get-url "$url" | sed -e "s/^/file '/" | sed -e "s/$/'/"
}

main() {
	local url=$1
	local station=$2
	ffmpeg -protocol_whitelist file,http,https,tcp,tls,crypto \
		-f concat -safe 0 -i <(yt-dlp-to-ffconcat "$url") \
		-f mp3 -ar 44100 -b:a 256k - | \
		cstream -t 64k | \
    	curl -s -k -H "Transfer-Encoding: chunked" -X POST -T -  \
    	"https://streammyaudio.com/$station.mp3?stream=true&advertise=true"
}

main "$@"
```

You can then make this script executable and use it like this:
```bash
./stream-playlist.bash "https://www.youtube.com/playlist?list=PL2D4C428C2C10BCFF" vgm
```

This is pretty awesome as it allows you to stream a lot of content and not have to download it to your PC! You can throw `shuf` into the mix as well with a big playlist and have music to listen to with your buds for hours!

If I feel like it, I might convert this into a Python script and use `aiohttp` to send a message about the currently playing song into chat. Perhaps I could even take requests via commands as well.

If you're awake when I create this issue, you can listen to the [Street Fighter 3 soundtrack](https://www.youtube.com/playlist?list=PL2D4C428C2C10BCFF) on [the vgm station](https://streammyaudio.com/vgm). This feels especially appropriate seeing as you made a blog post about drum and bass the other day.

**Comment by schollz** [comment]
Hey @SuperSonicHub1 that's one of the neatest little scripts I've seen in a long time!!

I had made something on a similar vein to playback files on my own computer

<details><summary>another script</summary>

```bash
find ~/Music/ | grep 'wav\|mp3\|flac' | shuf | sed -e "s/^/file '/" | \
    sed -e "s/$/'/" > /tmp/playlist.txt && \
    ffmpeg -f concat -safe 0 -i /tmp/playlist.txt -f mp3 -ar 44100 -b:a 256k - | \
    cstream -t 32k | \
    curl -s -k -H "Transfer-Encoding: chunked" -X POST -T -  \
    "https://streammyaudio,com/YOURSTATIONNAME.mp3?stream=true&advertise=true"
```
</details>

but yours is next level!! its like remixing the internet and streaming it back through the internet! love it. Would you like to PR your script? You could add it [right here](https://github.com/schollz/streammyaudio/blob/main/src/server/template/sya.html#L44) as an example of how to stream playlists! Or if you don't mind, I could add it and attribute you :)

In any case, very cool scriptfu and awesome station

**Comment by SuperSonicHub1** [comment]
I'd be happy to add it!

**Comment by SuperSonicHub1** [comment]
Just sent my pull! #3

**Comment by marclundgren** [comment]
@SuperSonicHub1 I can't seem to get `cstream` installed on a mac. tried `pip3 install cstream`, `python3 -m pip install -U cstream`. 

Everytime I try to run this script I get `cstream command not found`. Any tips?

**Comment by SuperSonicHub1** [comment]
@marclundgren [cstream](https://www.cons.org/cracauer/cstream.html) is written in C. cstream doesn't look to be on Homebrew, so you'll need to compile it yourself.

**Comment by blogdemoi** [comment]
Thank you, just compiled cstream on Manjaro to use your script, very nice.

**Comment by SuperSonicHub1** [comment]
@blogdemoi Glad to hear it! :)
