### ISSUE TITLE
Doesn't launch

### ISSUE THREAD

**Issue by blogdemoi** [schollz/streamyouraudio#4]
Hi,
Thank you for this. The command line works great but the Linux release doesn't launch on my Manjaro Xfce...

**Comment by blogdemoi** [comment]
Hum, I am sorry, it is working now, I can lauch it. Thank you again.

**Comment by schollz** [comment]
Great! I didn't have binaries for M1 mac, but now there is in case thats a problem for anyone else. I"ll close this then
