### ISSUE TITLE
windows client quits immediately after starting stream

### ISSUE THREAD

**Issue by Liam-DeVoe** [schollz/streamyouraudio#5]
using the windows client quits immediately after trying to start a stream:

https://user-images.githubusercontent.com/31628143/190949654-7b3baadb-0366-4300-9856-6124fbadf617.mp4

Might be related that the only input device option is `obs virtual camera (video` (sic) - this was the only option even when I wasn't running obs at all to record this video. I'm not sure what options are supposed to be there, but I was expecting something like "computer sound card".

**Comment by schollz** [comment]
Yeah seems like you don't have an audio input available

**Comment by Liam-DeVoe** [comment]
alright, sounds like an issue on my side then. Thanks.
